# Generated by Django 4.2.16 on 2024-11-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
    ]
